import type { TestInfo } from '@playwright/test';
import type { CaseRecord } from './config.js';

export function annotateCase(testInfo: TestInfo, record: CaseRecord, feature: string) {
  testInfo.annotations.push(
    { type: 'Run by', description: process.env.STUDENT_ID ?? '23127209' },
    { type: 'Feature', description: feature },
    { type: 'Browser', description: testInfo.project.name },
    { type: 'Run timestamp', description: process.env.RUN_TIMESTAMP ?? 'generated by Playwright config' },
    { type: 'Test case', description: record.id },
    { type: 'References', description: record.references.join(', ') }
  );
}
